// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQFW8Lfz57inwwtX15TTVYKZO0_WJjoow',
    appId: '1:862994765868:web:792f4d19143959449f9989',
    messagingSenderId: '862994765868',
    projectId: 'finanzatrack-97406',
    authDomain: 'finanzatrack-97406.firebaseapp.com',
    storageBucket: 'finanzatrack-97406.firebasestorage.app',
    measurementId: 'G-H2D3K2QJZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh8fJH4-QQWazfdH35HWwuQLdC4xTIKPc',
    appId: '1:862994765868:android:724b4803dfd78ccb9f9989',
    messagingSenderId: '862994765868',
    projectId: 'finanzatrack-97406',
    storageBucket: 'finanzatrack-97406.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEJoUpQYE1c_3YR9dG3E8d8qY-WtF4Kdk',
    appId: '1:862994765868:ios:7c1aecdc1c7ef9549f9989',
    messagingSenderId: '862994765868',
    projectId: 'finanzatrack-97406',
    storageBucket: 'finanzatrack-97406.firebasestorage.app',
    iosBundleId: 'com.example.finanzatrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEJoUpQYE1c_3YR9dG3E8d8qY-WtF4Kdk',
    appId: '1:862994765868:ios:7c1aecdc1c7ef9549f9989',
    messagingSenderId: '862994765868',
    projectId: 'finanzatrack-97406',
    storageBucket: 'finanzatrack-97406.firebasestorage.app',
    iosBundleId: 'com.example.finanzatrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQFW8Lfz57inwwtX15TTVYKZO0_WJjoow',
    appId: '1:862994765868:web:682aa1d4320211829f9989',
    messagingSenderId: '862994765868',
    projectId: 'finanzatrack-97406',
    authDomain: 'finanzatrack-97406.firebaseapp.com',
    storageBucket: 'finanzatrack-97406.firebasestorage.app',
    measurementId: 'G-X55QDPWGEE',
  );
}
